services:
  bytebin:
    image: ghcr.io/lucko/bytebin
    ports:
      - 3001:80
    volumes:
      - data:/opt/bytebin/content
      - db:/opt/bytebin/db
    environment:
      # You can configure bytebin using
      # environment variables.
      BYTEBIN_MISC_KEYLENGTH: 15
      BYTEBIN_CONTENT_MAXSIZE: 5

volumes:
  data: {}
  db: {}
